WIP: fallthrough routing
dymmond/lilya pull request #123
Opened 2024-12-26 04:40 UTC by devkral

Changes:

- add sniffer
- allow fallthrough routing (easier than thought, and without a generator)

### Checklist

- [ ] The code has 100% test coverage.
- [ ] The documentation was properly created or updated (if applicable) following the correct guidelines and appropriate language.
- [ ] I branched out from the latest main or is a sub-branch.

### Summary or description

2025-01-02 12:10 UTC, devkral commented
The biggest change in routing.py was moving Include to the end.

I will revert this so the PR is easier readable.

2025-01-06 08:09 UTC, tarsil requested changes

2025-01-06 08:09 UTC, tarsil commented on docs/en/docs/routing.md
> +Somewhere between both passes is `redirect_slashes` which causes the router to issue an redirect to an existing path in case a slash is missing or too much.
Lilya supports fall-through routing. This means that the routes of every router are checked sequentially until a complete match is found (both path and methods match) and no `lilya.exceptions.ContinueRouting` exception is raised. 

If no complete match is found, the router attempts to match the path only (partial match) and raises an appropriate exception. 

Additionally, the `redirect_slashes` feature issues a redirect to an existing path if a slash is either missing or excessive.

2025-01-06 08:09 UTC, tarsil commented on docs/en/docs/routing.md
> +The received first message is repeated for the next handler.
You can import with two Includes using the same path containing multiple routes. It's possible to have routes with the same path if the methods differ or if the first handler raises `lilya.exceptions.ContinueRouting` after a more detailed inspection. It's not an issue if `receive` was called **once** for the inspection. The first received message is repeated for the next handler.

2025-01-06 08:09 UTC, tarsil commented on docs/en/docs/routing.md
> +    Unfortunately there is no sniff method. So you have to be careful when sniffing the body (`Request`) for raising `lilya.exceptions.ContinueRouting`.
Unfortunately, there is no sniff method. Therefore, you must be cautious when inspecting the body (`Request`) to raise `lilya.exceptions.ContinueRouting`.

2025-01-06 08:09 UTC, tarsil commented on docs/en/docs/routing.md
> +This can be done by passing `redirect_slashes=False` to the `Include`.
It is even safer because a user named `me` cannot be accessed.

For performance reasons, let's assume we want to disable the `redirect_slashes` feature, but only for a performance-critical Include block. The rest is managed by an included ASGI app. This can be achieved by passing `redirect_slashes=False` to the `Include`.

2025-01-06 08:09 UTC, tarsil commented on docs/en/docs/static-files.md
> +You can also provide multiple `StaticFiles` and use `fall_through=True` for all except the last to keep the fall-through behavior.
You can provide multiple `StaticFiles` and set `fall_through=True` for all except the last one to maintain the fall-through behavior.

2025-01-07 10:09 UTC, tarsil commented
Once this is addressed then by the end of the week we release

2025-01-07 13:27 UTC, tarsil commented on docs/en/docs/routing.md
> +This can be done by passing `redirect_slashes=False` to the `Include`.
You forgot this but that is ok

2025-01-07 13:28 UTC, merged