Update jinja.py
dymmond/lilya pull request #39
Opened 2024-03-11 16:43 UTC by Kokoserver

Update the get_template_response docs

### Checklist

- [ ] The code has 100% test coverage.
- [ ] The documentation was properly created or updated (if applicable) following the correct guidelines and appropriate language.
- [ ] I branched out from the latest main or is a sub-branch.

2024-03-11 16:54 UTC, tarsil commented
Don't understand why the runner is not running. Did you run the tests locally?

2024-03-11 22:37 UTC, tarsil requested changes

2024-03-11 22:37 UTC, tarsil commented on lilya/templating/jinja.py
> +        Any additional arguments or keyword arguments provided will be passed directly to the
Space (enter) here, please 👍🏼

2024-03-12 13:11 UTC, tarsil commented
@Kokoserver in the contributing tells you how to do it. You should run the `scripts/check` and `scripts/lint` before pushing to fix any error.

2024-03-12 13:31 UTC, Kokoserver commented
i will do that right away

2024-03-12 21:47 UTC, closed without merging